//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:16</p>
  /// </summary>
  public class MyBackendModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<MyFindRequest, StatementInfo[]> GetFunctionNames => _GetFunctionNames;
    
    //private fields
    [NotNull] private readonly RdCall<MyFindRequest, StatementInfo[]> _GetFunctionNames;
    
    //primary constructor
    private MyBackendModel(
      [NotNull] RdCall<MyFindRequest, StatementInfo[]> getFunctionNames
    )
    {
      if (getFunctionNames == null) throw new ArgumentNullException("getFunctionNames");
      
      _GetFunctionNames = getFunctionNames;
      BindableChildren.Add(new KeyValuePair<string, object>("getFunctionNames", _GetFunctionNames));
    }
    //secondary constructor
    internal MyBackendModel (
    ) : this (
      new RdCall<MyFindRequest, StatementInfo[]>(MyFindRequest.Read, MyFindRequest.Write, ReadStatementInfoArray, WriteStatementInfoArray)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<StatementInfo[]> ReadStatementInfoArray = StatementInfo.Read.Array();
    
    public static  CtxWriteDelegate<StatementInfo[]> WriteStatementInfoArray = StatementInfo.Write.Array();
    
    protected override long SerializationHash => 4223364129162007567L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("MyBackendModel (");
      using (printer.IndentCookie()) {
        printer.Print("getFunctionNames = "); _GetFunctionNames.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionMyBackendModelEx
   {
    public static MyBackendModel GetMyBackendModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("myBackendModel", () => new MyBackendModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:23</p>
  /// </summary>
  public sealed class MyFindRequest : IPrintable, IEquatable<MyFindRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    public int CaretOffset {get; private set;}
    
    //private fields
    //primary constructor
    public MyFindRequest(
      [NotNull] string filePath,
      int caretOffset
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      FilePath = filePath;
      CaretOffset = caretOffset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, out int caretOffset)
    {
      filePath = FilePath;
      caretOffset = CaretOffset;
    }
    //statics
    
    public static CtxReadDelegate<MyFindRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var caretOffset = reader.ReadInt();
      var _result = new MyFindRequest(filePath, caretOffset);
      return _result;
    };
    
    public static CtxWriteDelegate<MyFindRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.CaretOffset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MyFindRequest) obj);
    }
    public bool Equals(MyFindRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && CaretOffset == other.CaretOffset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + CaretOffset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MyFindRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("caretOffset = "); CaretOffset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:29</p>
  /// </summary>
  public sealed class StatementInfo : IPrintable, IEquatable<StatementInfo>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    public int Offset {get; private set;}
    
    //private fields
    //primary constructor
    public StatementInfo(
      [NotNull] string name,
      int offset
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      
      Name = name;
      Offset = offset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, out int offset)
    {
      name = Name;
      offset = Offset;
    }
    //statics
    
    public static CtxReadDelegate<StatementInfo> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var offset = reader.ReadInt();
      var _result = new StatementInfo(name, offset);
      return _result;
    };
    
    public static CtxWriteDelegate<StatementInfo> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.Offset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((StatementInfo) obj);
    }
    public bool Equals(StatementInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && Offset == other.Offset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + Offset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("StatementInfo (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("offset = "); Offset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
