//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:16</p>
  /// </summary>
  public class MyBackendModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<MyFindRequest, WalkedResult> GetFunctionNames => _GetFunctionNames;
    
    //private fields
    [NotNull] private readonly RdCall<MyFindRequest, WalkedResult> _GetFunctionNames;
    
    //primary constructor
    private MyBackendModel(
      [NotNull] RdCall<MyFindRequest, WalkedResult> getFunctionNames
    )
    {
      if (getFunctionNames == null) throw new ArgumentNullException("getFunctionNames");
      
      _GetFunctionNames = getFunctionNames;
      BindableChildren.Add(new KeyValuePair<string, object>("getFunctionNames", _GetFunctionNames));
    }
    //secondary constructor
    internal MyBackendModel (
    ) : this (
      new RdCall<MyFindRequest, WalkedResult>(MyFindRequest.Read, MyFindRequest.Write, WalkedResult.Read, WalkedResult.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -7067078345171135611L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("MyBackendModel (");
      using (printer.IndentCookie()) {
        printer.Print("getFunctionNames = "); _GetFunctionNames.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionMyBackendModelEx
   {
    public static MyBackendModel GetMyBackendModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("myBackendModel", () => new MyBackendModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:23</p>
  /// </summary>
  public sealed class MyFindRequest : IPrintable, IEquatable<MyFindRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    public int CaretOffset {get; private set;}
    
    //private fields
    //primary constructor
    public MyFindRequest(
      [NotNull] string filePath,
      int caretOffset
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      FilePath = filePath;
      CaretOffset = caretOffset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, out int caretOffset)
    {
      filePath = FilePath;
      caretOffset = CaretOffset;
    }
    //statics
    
    public static CtxReadDelegate<MyFindRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var caretOffset = reader.ReadInt();
      var _result = new MyFindRequest(filePath, caretOffset);
      return _result;
    };
    
    public static CtxWriteDelegate<MyFindRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.CaretOffset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MyFindRequest) obj);
    }
    public bool Equals(MyFindRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && CaretOffset == other.CaretOffset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + CaretOffset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MyFindRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("caretOffset = "); CaretOffset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:29</p>
  /// </summary>
  public sealed class StatementInfo : IPrintable, IEquatable<StatementInfo>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    public int Offset {get; private set;}
    
    //private fields
    //primary constructor
    public StatementInfo(
      [NotNull] string name,
      int offset
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      
      Name = name;
      Offset = offset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, out int offset)
    {
      name = Name;
      offset = Offset;
    }
    //statics
    
    public static CtxReadDelegate<StatementInfo> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var offset = reader.ReadInt();
      var _result = new StatementInfo(name, offset);
      return _result;
    };
    
    public static CtxWriteDelegate<StatementInfo> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.Offset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((StatementInfo) obj);
    }
    public bool Equals(StatementInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && Offset == other.Offset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + Offset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("StatementInfo (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("offset = "); Offset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:34</p>
  /// </summary>
  public sealed class WalkedFunction : IPrintable, IEquatable<WalkedFunction>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string Path {get; private set;}
    public int Offset {get; private set;}
    [NotNull] public List<StatementInfo> Statements {get; private set;}
    
    //private fields
    //primary constructor
    public WalkedFunction(
      [NotNull] string name,
      [NotNull] string path,
      int offset,
      [NotNull] List<StatementInfo> statements
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (path == null) throw new ArgumentNullException("path");
      if (statements == null) throw new ArgumentNullException("statements");
      
      Name = name;
      Path = path;
      Offset = offset;
      Statements = statements;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string path, out int offset, [NotNull] out List<StatementInfo> statements)
    {
      name = Name;
      path = Path;
      offset = Offset;
      statements = Statements;
    }
    //statics
    
    public static CtxReadDelegate<WalkedFunction> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var path = reader.ReadString();
      var offset = reader.ReadInt();
      var statements = ReadStatementInfoList(ctx, reader);
      var _result = new WalkedFunction(name, path, offset, statements);
      return _result;
    };
    public static CtxReadDelegate<List<StatementInfo>> ReadStatementInfoList = StatementInfo.Read.List();
    
    public static CtxWriteDelegate<WalkedFunction> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.Path);
      writer.Write(value.Offset);
      WriteStatementInfoList(ctx, writer, value.Statements);
    };
    public static  CtxWriteDelegate<List<StatementInfo>> WriteStatementInfoList = StatementInfo.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((WalkedFunction) obj);
    }
    public bool Equals(WalkedFunction other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && Path == other.Path && Offset == other.Offset && Statements.SequenceEqual(other.Statements);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + Path.GetHashCode();
        hash = hash * 31 + Offset.GetHashCode();
        hash = hash * 31 + Statements.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("WalkedFunction (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("path = "); Path.PrintEx(printer); printer.Println();
        printer.Print("offset = "); Offset.PrintEx(printer); printer.Println();
        printer.Print("statements = "); Statements.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MyBackendModel.kt:41</p>
  /// </summary>
  public sealed class WalkedResult : IPrintable, IEquatable<WalkedResult>
  {
    //fields
    //public fields
    [NotNull] public WalkedFunction Current {get; private set;}
    [NotNull] public List<WalkedFunction> Usages {get; private set;}
    
    //private fields
    //primary constructor
    public WalkedResult(
      [NotNull] WalkedFunction current,
      [NotNull] List<WalkedFunction> usages
    )
    {
      if (current == null) throw new ArgumentNullException("current");
      if (usages == null) throw new ArgumentNullException("usages");
      
      Current = current;
      Usages = usages;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out WalkedFunction current, [NotNull] out List<WalkedFunction> usages)
    {
      current = Current;
      usages = Usages;
    }
    //statics
    
    public static CtxReadDelegate<WalkedResult> Read = (ctx, reader) => 
    {
      var current = WalkedFunction.Read(ctx, reader);
      var usages = ReadWalkedFunctionList(ctx, reader);
      var _result = new WalkedResult(current, usages);
      return _result;
    };
    public static CtxReadDelegate<List<WalkedFunction>> ReadWalkedFunctionList = WalkedFunction.Read.List();
    
    public static CtxWriteDelegate<WalkedResult> Write = (ctx, writer, value) => 
    {
      WalkedFunction.Write(ctx, writer, value.Current);
      WriteWalkedFunctionList(ctx, writer, value.Usages);
    };
    public static  CtxWriteDelegate<List<WalkedFunction>> WriteWalkedFunctionList = WalkedFunction.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((WalkedResult) obj);
    }
    public bool Equals(WalkedResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Current, other.Current) && Usages.SequenceEqual(other.Usages);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Current.GetHashCode();
        hash = hash * 31 + Usages.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("WalkedResult (");
      using (printer.IndentCookie()) {
        printer.Print("current = "); Current.PrintEx(printer); printer.Println();
        printer.Print("usages = "); Usages.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
